### ISSUE TITLE
Add anchor link for titles in documents

### ISSUE THREAD

**Issue by zcbenz** [atom/electron.atom.io#34]
It is useful to use link with hash to reference a certain API in the documents, like this:
https://github.com/atom/electron/blob/master/docs/api/tray.md#traysethighlightmodehighlight

**Comment by jlord** [comment]
I added the id option to the site's markdown parser, https://github.com/atom/electron.atom.io/commit/1c24753b5fbc28aa86027e4096df17c196318c37 so it now adds an id. But looking at the example you mentioned, the id is a bit awkward for methods:

```html
<h3 id="tray.sethighlightmode(highlight)">Tray.setHighlightMode(highlight)</h3>
```
Also, that id doesn't even work as an anchor :disappointed: 

We are using `redcarpet` as the parser because it worked best with highlighting (I think), but I will try and experiment with another so that these work.

**Comment by jlord** [comment]
When GitHub Pages updates the version of `redcarpet` it uses our ids will get sorted :pizza: 

Things in motion: https://github.com/github/pages-gem/pull/143

**Comment by jlord** [comment]
The parser has been updated so our docs now have the ids: http://electron.atom.io/docs/v0.30.0/api/tray/#tray-sethighlightmode-highlight

I just dug around and found the way to get the headers to be links in Jekyll as well... PR coming :soon:
