### ISSUE TITLE
Incorrect documentation for browser window options

### ISSUE THREAD

**Issue by hokein** [atom/electron.atom.io#59]
Moved from atom/electron#2342.

The documentation for browser window options lacks proper indentation. Everything below web-preferences should be indented one level. Currently it looks like, for example, text-areas-are-resizable is a property of options while it is a property of web-preferences. The Markdown seems to be OK, but the documentation page isn't properly indented.

**Comment by jlord** [comment]
Interesting. So it looks like this is a problem with the Markdown parser we use, `redcarpet`, having limited nesting (see [issue comment](https://github.com/vmg/redcarpet/issues/115#issuecomment-4187069)). 

I wasn't aware of this limit and will have a think about what's best to do. Switching [GitHub Pages supported] markdown parsers won't work because the other doesn't work with the way we're writing code blocks, so it may be that we end up building the whole site locally and pushing it so that we can use custom gems to get the rendered Markdown we're expecting.

**Comment by jlord** [comment]
An update, I'm working on going through the documentation over on `atom/electron` and in doing so I'm making sure we don't nest 3 deep in lists. When those are updated here then we can close this.

**Comment by jlord** [comment]
The docs have been updated and indentation fixed :sparkles:

**Comment by mn4367** [comment]
Thanks!
